---
title: "Research"
toc: false
page-layout: article
---

## **Peer-Reviewed Articles**
::: {.callout-warning appearance="simple" icon="false"}
* Dey, D. K., & **Ndreka, B. (2022)**. The latent-space adjusted approach: An alternative form in modeling economic
development and forest cover. International Journal of Statistical Sciences, 22(1), 197–212.

:::
## **Working Papers**
::: {.callout-warning appearance="simple" icon="false"}

* **Ndreka, B.**, K.Dey, D., & Lachos, V. H. (2023). Bayesian estimation of contagion effect: An application of
friendship networks and alcohol behavior. [Under review.].

* **Ndreka, B.**, K.Dey, D., & Xu, R. (2023). Comparison of methods for estimating contagion effect in a social
network analysis [Under review.].

* **Ndreka, B.**, K.Dey, D., & Lacho, V. H. (2024). Bayesian inference for social influence estimation via a skewed
link function in modeling social selection [Working paper.].

:::


##  **Conference Presentations**
::: {.callout-warning appearance="simple" icon="false"}

* Alcohol-Contagion Effect within Teenage Friendships. *Pushing the Boundary of Data Science through Statistical Modeling and Inference. Blacksburg, VA, 2023*.

* Bayesian Estimation of Contagion Effect. *The 35th New England Statistics Symposium Boston, MA, 2023*.

* Peer of International Trade Between European Countries. *A Special Conference Celebrating UConn Department of Statistics 60th Anniversary Storrs, CT*.


:::




